Kornel motyka
ArsenEloglian/AdvanceProgrammingTechniques_2122 pull request #165
Opened 2021-11-18 18:02 UTC by Cornyy

2021-11-18 18:04 UTC, ArsenEloglian requested changes
Please update PR header

2021-11-18 18:06 UTC, Cornyy commented
#

> Please update PR header

done

2021-11-18 18:09 UTC, michple reviewed
Program problemCollatza.cpp wykonuje o jeden test za dużo
`int counter, a, b;
    cin>>counter;
    for(int i=0;i<=counter;i++)
    {`
W powyższej pętli for warunek końca powinien być '<' zamiast '<='
Dodatkowo funkcja main() nie musi posiadać lini "return 0;"

2021-11-18 18:13 UTC, Cornyy commented
> Program problemCollatza.cpp wykonuje o jeden test za dużo `int counter, a, b; cin>>counter; for(int i=0;i<=counter;i++) {` W powyższej pętli for warunek końca powinien być '<' zamiast '<=' Dodatkowo funkcja main() nie musi posiadać lini "return 0;"

done

2021-11-18 18:14 UTC, michple approved these changes

2021-11-19 09:01 UTC, ArsenEloglian approved these changes

2021-11-19 09:04 UTC, merged